server:
  port: ${server.port}
  servlet:
    context-path: ${server.servlet.context-path}
spring:
  profiles:
    active: ${spring.profiles.active}
  datasource:
    druid:
      # JDBC配置
      url: ${spring.datasource.druid.url}
      username: ${spring.datasource.druid.username}
      password: ${spring.datasource.druid.password}
      driver-class-name: ${spring.datasource.druid.driver-class-name}

      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: ${spring.datasource.druid.initial-size}
      max-active: ${spring.datasource.druid.max-active}
      min-idle: ${spring.datasource.druid.min-idle}
      # 获取连接等待超时时间
      max-wait: ${spring.datasource.druid.max-wait}
      pool-prepared-statements: ${spring.datasource.druid.pool-prepared-statements}
      #
      validation-query: ${spring.datasource.druid.validation-query}
      test-on-borrow: ${spring.datasource.druid.test-on-borrow}
      test-on-return: ${spring.datasource.druid.test-on-return}
      test-while-idle: ${spring.datasource.druid.test-while-idle}
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: ${spring.datasource.druid.time-between-eviction-runs-millis}
      # 一个连接在连接池中最小的生存时间
      min-evictable-idle-time-millis: ${spring.datasource.druid.min-evictable-idle-time-millis}
      max-pool-prepared-statement-per-connection-size: ${spring.datasource.druid.max-pool-prepared-statement-per-connection-size}
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: ${spring.datasource.druid.use-global-data-source-stat}
      filters: ${spring.datasource.druid.filters}
      filter:
        # 慢SQL记录(sql语句执行时间超过某个界限就记录下来)
        stat:
          slow-sql-millis: ${spring.datasource.druid.filter.stat.slow-sql-millis}
          log-slow-sql: ${spring.datasource.druid.filter.stat.log-slow-sql}

      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: ${spring.datasource.druid.web-stat-filter.enabled}
        url-pattern: ${spring.datasource.druid.web-stat-filter.url-pattern}
        exclusions: ${spring.datasource.druid.web-stat-filter.exclusions}
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: ${spring.datasource.druid.stat-view-servlet.enabled}
        url-pattern: ${spring.datasource.druid.stat-view-servlet.url-pattern}
        # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
        login-username: ${spring.datasource.druid.stat-view-servlet.login-username}
        login-password: ${spring.datasource.druid.stat-view-servlet.login-password}
        allow:
        deny:
mybatis:
  mapper-locations: ${mybatis.mapper-locations}
  type-aliases-package: ${mybatis.type-aliases-package}
pagehelper:
  helper-dialect: ${pagehelper.helper-dialect}
  reasonable: ${pagehelper.reasonable}
  support-methods-arguments: ${pagehelper.support-methods-arguments}
  params: ${pagehelper.params}
sms:
  chuanglan:
    accessKey: ${sms.chuanglan.accessKey}
    accessKey.international: ${sms.chuanglan.accessKey.international}
    secretKey: ${sms.chuanglan.secretKey}
    secretKey.international: ${sms.chuanglan.secretKey.international}
    url: ${sms.chuanglan.url}
    url.international: ${sms.chuanglan.url.international}
  globalsent:
    accessKey: ${sms.globalsent.accessKey}
    callBackUrl: ${sms.globalsent.callBackUrl}
    url: ${sms.globalsent.url}
  meilian:
    apikey: ${sms.meilian.apikey}
    password: ${sms.meilian.password}
    url: ${sms.meilian.url}
    userName: ${sms.meilian.userName}
  zt:
    productid: ${sms.zt.productid}
    password: ${sms.zt.password}
    url: ${sms.zt.url}
    userName: ${sms.zt.userName}
time-zone: GMT+8
smsTemplate:
  otc:
    zh: ${smsTemplate.otc.zh}
    en: ${smsTemplate.otc.en}
    ko: ${smsTemplate.otc.ko}