package com.hotcoin.notice.entity;

import com.hotcoin.notice.util.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class EmailMessageEntity extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.email
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.title
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.system_code
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String systemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.template_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.status
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.send_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message.content
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.id
     *
     * @return the value of email_message.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.id
     *
     * @param id the value for email_message.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.email
     *
     * @return the value of email_message.email
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.email
     *
     * @param email the value for email_message.email
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.title
     *
     * @return the value of email_message.title
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.title
     *
     * @param title the value for email_message.title
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.system_code
     *
     * @return the value of email_message.system_code
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.system_code
     *
     * @param systemCode the value for email_message.system_code
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.template_id
     *
     * @return the value of email_message.template_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.template_id
     *
     * @param templateId the value for email_message.template_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.status
     *
     * @return the value of email_message.status
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.status
     *
     * @param status the value for email_message.status
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.create_time
     *
     * @return the value of email_message.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.create_time
     *
     * @param createTime the value for email_message.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.send_time
     *
     * @return the value of email_message.send_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.send_time
     *
     * @param sendTime the value for email_message.send_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.version
     *
     * @return the value of email_message.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.version
     *
     * @param version the value for email_message.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message.content
     *
     * @return the value of email_message.content
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message.content
     *
     * @param content the value for email_message.content
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", email=").append(email);
        sb.append(", title=").append(title);
        sb.append(", systemCode=").append(systemCode);
        sb.append(", templateId=").append(templateId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", version=").append(version);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}