package com.hotcoin.notice.entity;

import com.hotcoin.notice.util.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class MessageTemplateEntity extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.lang
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String lang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.business_type
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.type
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.platform
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.delete
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Boolean delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.description
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.update_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_template
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.id
     *
     * @return the value of message_template.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.id
     *
     * @param id the value for message_template.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.lang
     *
     * @return the value of message_template.lang
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.lang
     *
     * @param lang the value for message_template.lang
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.business_type
     *
     * @return the value of message_template.business_type
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.business_type
     *
     * @param businessType the value for message_template.business_type
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.type
     *
     * @return the value of message_template.type
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.type
     *
     * @param type the value for message_template.type
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.platform
     *
     * @return the value of message_template.platform
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.platform
     *
     * @param platform the value for message_template.platform
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.delete
     *
     * @return the value of message_template.delete
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.delete
     *
     * @param delete the value for message_template.delete
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.description
     *
     * @return the value of message_template.description
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.description
     *
     * @param description the value for message_template.description
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.create_time
     *
     * @return the value of message_template.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.create_time
     *
     * @param createTime the value for message_template.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.update_time
     *
     * @return the value of message_template.update_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.update_time
     *
     * @param updateTime the value for message_template.update_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.version
     *
     * @return the value of message_template.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.version
     *
     * @param version the value for message_template.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template
     *
     * @return the value of message_template.template
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template
     *
     * @param template the value for message_template.template
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_template
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", lang=").append(lang);
        sb.append(", businessType=").append(businessType);
        sb.append(", type=").append(type);
        sb.append(", platform=").append(platform);
        sb.append(", delete=").append(delete);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", version=").append(version);
        sb.append(", template=").append(template);
        sb.append("]");
        return sb.toString();
    }
}