package com.hotcoin.notice.entity;

import com.hotcoin.notice.util.BaseModel;
import java.io.Serializable;

public class SmsConfigEntity extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_config.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_config.name
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_config.enable
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_config.weight
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_config.description
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_config.action
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_config.id
     *
     * @return the value of sms_config.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_config.id
     *
     * @param id the value for sms_config.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_config.name
     *
     * @return the value of sms_config.name
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_config.name
     *
     * @param name the value for sms_config.name
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_config.enable
     *
     * @return the value of sms_config.enable
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_config.enable
     *
     * @param enable the value for sms_config.enable
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_config.weight
     *
     * @return the value of sms_config.weight
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_config.weight
     *
     * @param weight the value for sms_config.weight
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_config.description
     *
     * @return the value of sms_config.description
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_config.description
     *
     * @param description the value for sms_config.description
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_config.action
     *
     * @return the value of sms_config.action
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_config.action
     *
     * @param action the value for sms_config.action
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", enable=").append(enable);
        sb.append(", weight=").append(weight);
        sb.append(", description=").append(description);
        sb.append(", action=").append(action);
        sb.append("]");
        return sb.toString();
    }
}