package com.hotcoin.notice.entity;

import com.hotcoin.notice.util.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class SmsMessageEntity extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.phone
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.send_channel
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String sendChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.platform
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.template_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.status
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.send_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.third_msg_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String thirdMsgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.content
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.id
     *
     * @return the value of sms_message.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.id
     *
     * @param id the value for sms_message.id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.phone
     *
     * @return the value of sms_message.phone
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.phone
     *
     * @param phone the value for sms_message.phone
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.send_channel
     *
     * @return the value of sms_message.send_channel
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getSendChannel() {
        return sendChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.send_channel
     *
     * @param sendChannel the value for sms_message.send_channel
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setSendChannel(String sendChannel) {
        this.sendChannel = sendChannel == null ? null : sendChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.platform
     *
     * @return the value of sms_message.platform
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.platform
     *
     * @param platform the value for sms_message.platform
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.template_id
     *
     * @return the value of sms_message.template_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.template_id
     *
     * @param templateId the value for sms_message.template_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.status
     *
     * @return the value of sms_message.status
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.status
     *
     * @param status the value for sms_message.status
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.create_time
     *
     * @return the value of sms_message.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.create_time
     *
     * @param createTime the value for sms_message.create_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.send_time
     *
     * @return the value of sms_message.send_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.send_time
     *
     * @param sendTime the value for sms_message.send_time
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.version
     *
     * @return the value of sms_message.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.version
     *
     * @param version the value for sms_message.version
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.third_msg_id
     *
     * @return the value of sms_message.third_msg_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getThirdMsgId() {
        return thirdMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.third_msg_id
     *
     * @param thirdMsgId the value for sms_message.third_msg_id
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setThirdMsgId(String thirdMsgId) {
        this.thirdMsgId = thirdMsgId == null ? null : thirdMsgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.content
     *
     * @return the value of sms_message.content
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.content
     *
     * @param content the value for sms_message.content
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", sendChannel=").append(sendChannel);
        sb.append(", platform=").append(platform);
        sb.append(", templateId=").append(templateId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", version=").append(version);
        sb.append(", thirdMsgId=").append(thirdMsgId);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}