package com.qkwl.common.entity;

import java.io.Serializable;
import java.util.Date;

public class OpenApiEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.id
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.url
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.status
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.types
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private String types;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.if_sign_verify
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private Boolean ifSignVerify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.description
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.create_time
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_api.update_time
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.id
     *
     * @return the value of open_api.id
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.id
     *
     * @param id the value for open_api.id
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.url
     *
     * @return the value of open_api.url
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.url
     *
     * @param url the value for open_api.url
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.status
     *
     * @return the value of open_api.status
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.status
     *
     * @param status the value for open_api.status
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.types
     *
     * @return the value of open_api.types
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.types
     *
     * @param types the value for open_api.types
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.if_sign_verify
     *
     * @return the value of open_api.if_sign_verify
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public Boolean getIfSignVerify() {
        return ifSignVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.if_sign_verify
     *
     * @param ifSignVerify the value for open_api.if_sign_verify
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setIfSignVerify(Boolean ifSignVerify) {
        this.ifSignVerify = ifSignVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.description
     *
     * @return the value of open_api.description
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.description
     *
     * @param description the value for open_api.description
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.create_time
     *
     * @return the value of open_api.create_time
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.create_time
     *
     * @param createTime the value for open_api.create_time
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_api.update_time
     *
     * @return the value of open_api.update_time
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_api.update_time
     *
     * @param updateTime the value for open_api.update_time
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", url=").append(url);
        sb.append(", status=").append(status);
        sb.append(", types=").append(types);
        sb.append(", ifSignVerify=").append(ifSignVerify);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}