package com.qkwl.common.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserCoinWalletEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.id
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.uid
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.coin_id
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private Integer coinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.total
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.frozen
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private BigDecimal frozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.borrow
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private BigDecimal borrow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.ico
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private BigDecimal ico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.gmt_create
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.gmt_modified
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.version
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.deposit_frozen
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private BigDecimal depositFrozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coin_wallet.deposit_frozen_total
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private BigDecimal depositFrozenTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_coin_wallet
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.id
     *
     * @return the value of user_coin_wallet.id
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.id
     *
     * @param id the value for user_coin_wallet.id
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.uid
     *
     * @return the value of user_coin_wallet.uid
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.uid
     *
     * @param uid the value for user_coin_wallet.uid
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.coin_id
     *
     * @return the value of user_coin_wallet.coin_id
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public Integer getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.coin_id
     *
     * @param coinId the value for user_coin_wallet.coin_id
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setCoinId(Integer coinId) {
        this.coinId = coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.total
     *
     * @return the value of user_coin_wallet.total
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.total
     *
     * @param total the value for user_coin_wallet.total
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.frozen
     *
     * @return the value of user_coin_wallet.frozen
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public BigDecimal getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.frozen
     *
     * @param frozen the value for user_coin_wallet.frozen
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setFrozen(BigDecimal frozen) {
        this.frozen = frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.borrow
     *
     * @return the value of user_coin_wallet.borrow
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public BigDecimal getBorrow() {
        return borrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.borrow
     *
     * @param borrow the value for user_coin_wallet.borrow
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setBorrow(BigDecimal borrow) {
        this.borrow = borrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.ico
     *
     * @return the value of user_coin_wallet.ico
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public BigDecimal getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.ico
     *
     * @param ico the value for user_coin_wallet.ico
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setIco(BigDecimal ico) {
        this.ico = ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.gmt_create
     *
     * @return the value of user_coin_wallet.gmt_create
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.gmt_create
     *
     * @param gmtCreate the value for user_coin_wallet.gmt_create
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.gmt_modified
     *
     * @return the value of user_coin_wallet.gmt_modified
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.gmt_modified
     *
     * @param gmtModified the value for user_coin_wallet.gmt_modified
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.version
     *
     * @return the value of user_coin_wallet.version
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.version
     *
     * @param version the value for user_coin_wallet.version
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.deposit_frozen
     *
     * @return the value of user_coin_wallet.deposit_frozen
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public BigDecimal getDepositFrozen() {
        return depositFrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.deposit_frozen
     *
     * @param depositFrozen the value for user_coin_wallet.deposit_frozen
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setDepositFrozen(BigDecimal depositFrozen) {
        this.depositFrozen = depositFrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin_wallet.deposit_frozen_total
     *
     * @return the value of user_coin_wallet.deposit_frozen_total
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public BigDecimal getDepositFrozenTotal() {
        return depositFrozenTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin_wallet.deposit_frozen_total
     *
     * @param depositFrozenTotal the value for user_coin_wallet.deposit_frozen_total
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    public void setDepositFrozenTotal(BigDecimal depositFrozenTotal) {
        this.depositFrozenTotal = depositFrozenTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coin_wallet
     *
     * @mbg.generated Fri Nov 22 15:34:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", coinId=").append(coinId);
        sb.append(", total=").append(total);
        sb.append(", frozen=").append(frozen);
        sb.append(", borrow=").append(borrow);
        sb.append(", ico=").append(ico);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", version=").append(version);
        sb.append(", depositFrozen=").append(depositFrozen);
        sb.append(", depositFrozenTotal=").append(depositFrozenTotal);
        sb.append("]");
        return sb.toString();
    }
}