spring:
  datasource:
    name:
    url: jdbc:mysql://drdshgjh88nk8n1f.drds.aliyuncs.com:3306/hotcoin?useUnicode=true&characterEncoding=utf-8
    username: hotcoin
    password: Tubao502
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 50
    defaultAutoCommit: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
redis:
  host: r-j6cbgjk0b21q4tqvg2.redis.rds.aliyuncs.com
  port: 6379
  password: Tubao502310
  timeout: 5000
  pool:
    minIdle: 50
    maxIdle: 50
    maxTotal: 200
    maxWaitMillis: 5000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    
server:
  port: 8093