package com.qkwl.service.user.dao.base;

import com.qkwl.common.entity.ApiKeyEntity;
import com.qkwl.common.entity.ApiKeyEntityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiKeyBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    long countByExample(ApiKeyEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int deleteByExample(ApiKeyEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int insert(ApiKeyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int insertSelective(ApiKeyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    List<ApiKeyEntity> selectByExample(ApiKeyEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") ApiKeyEntity record, @Param("example") ApiKeyEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int updateByExample(@Param("record") ApiKeyEntity record, @Param("example") ApiKeyEntityCriteria example);
}