package com.qkwl.service.user.dao.base;

import com.qkwl.common.entity.OpenApiEntity;
import com.qkwl.common.entity.OpenApiEntityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpenApiBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    long countByExample(OpenApiEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int deleteByExample(OpenApiEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int insert(OpenApiEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int insertSelective(OpenApiEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    List<OpenApiEntity> selectByExample(OpenApiEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") OpenApiEntity record, @Param("example") OpenApiEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_api
     *
     * @mbg.generated Mon Nov 04 20:39:23 CST 2019
     */
    int updateByExample(@Param("record") OpenApiEntity record, @Param("example") OpenApiEntityCriteria example);
}