package com.hotcoin.notice.dao.base;

import com.hotcoin.notice.entity.EmailMessageEntity;
import com.hotcoin.notice.entity.EmailMessageEntityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailMessageBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    long countByExample(EmailMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int deleteByExample(EmailMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int insert(EmailMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int insertSelective(EmailMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    List<EmailMessageEntity> selectByExampleWithBLOBs(EmailMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    List<EmailMessageEntity> selectByExample(EmailMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") EmailMessageEntity record, @Param("example") EmailMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") EmailMessageEntity record, @Param("example") EmailMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExample(@Param("record") EmailMessageEntity record, @Param("example") EmailMessageEntityCriteria example);
}