package com.hotcoin.notice.dao.base;

import com.hotcoin.notice.entity.SmsConfigEntity;
import com.hotcoin.notice.entity.SmsConfigEntityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsConfigBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    long countByExample(SmsConfigEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int deleteByExample(SmsConfigEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int insert(SmsConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int insertSelective(SmsConfigEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    List<SmsConfigEntity> selectByExample(SmsConfigEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmsConfigEntity record, @Param("example") SmsConfigEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_config
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExample(@Param("record") SmsConfigEntity record, @Param("example") SmsConfigEntityCriteria example);
}