package com.hotcoin.notice.dao.base;

import com.hotcoin.notice.entity.SmsMessageEntity;
import com.hotcoin.notice.entity.SmsMessageEntityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsMessageBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    long countByExample(SmsMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int deleteByExample(SmsMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int insert(SmsMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int insertSelective(SmsMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    List<SmsMessageEntity> selectByExampleWithBLOBs(SmsMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    List<SmsMessageEntity> selectByExample(SmsMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmsMessageEntity record, @Param("example") SmsMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SmsMessageEntity record, @Param("example") SmsMessageEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_message
     *
     * @mbg.generated Thu Aug 01 10:09:29 CST 2019
     */
    int updateByExample(@Param("record") SmsMessageEntity record, @Param("example") SmsMessageEntityCriteria example);
}